# Generated by Django 3.2.19 on 2023-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllableContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('syllable', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
