# Generated by Django 3.2.19 on 2023-06-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict_result',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='predict_result',
            name='stage',
        ),
    ]
