# Generated by Django 3.2.19 on 2023-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_syllablecontent_wordcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game'),
        ),
    ]
