# Generated by Django 3.2.19 on 2023-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kakao_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
