# Generated by Django 3.2.19 on 2023-06-23 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('radio_field', models.CharField(choices=[('normal', '일반'), ('announcement', '공지')], default='normal', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='font_data_uploads/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='font_blog_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='fonts/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='font_blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_blog_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
