# Generated by Django 3.2.19 on 2023-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('font', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
    ]
