# Generated by Django 3.2.19 on 2023-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('font', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='practice')),
            ],
        ),
        migrations.CreateModel(
            name='Predict_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=500)),
                ('ground_truth', models.CharField(max_length=500)),
                ('confidence', models.FloatField()),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SentenceContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
