# Generated by Django 3.2.19 on 2023-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicecontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
